[build]
  # Directory to change to before starting a build
  base = "frontend/"
  
  # Directory that contains the deploy-ready HTML files and assets
  publish = "frontend/build/"
  
  # Build command to run
  command = "yarn install --frozen-lockfile && yarn build"

[build.environment]
  # Use specific Node.js version
  NODE_VERSION = "18"
  # Use Yarn instead of npm
  YARN_VERSION = "1.22.22"
  # Disable npm usage
  NPM_FLAGS = "--no-optional"

# Settings for Netlify's deploy preview feature
[context.deploy-preview]
  command = "yarn install --frozen-lockfile && yarn build"

[context.branch-deploy]
  command = "yarn install --frozen-lockfile && yarn build"

# Redirect rules for Single Page Application (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache optimization for static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"