[build]
  base = "frontend"
  publish = "frontend/build"
  command = "npm install && npm run build"

[build.environment]
  NODE_VERSION = "18.17.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200