[build]
  base = "frontend/"
  publish = "frontend/build/"
  command = "npm install && npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-optional"

# Redirect rules for Single Page Application (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200